### ISSUE TITLE
test_ST_VORONOIJTSInvalid()

### ISSUE THREAD

**Issue by obonin** [irstv/H2GIS#473]
The test_ST_VORONOIJTSInvalid() is broken since the last commit (in my forked repository, 1.2.X branch).
OB

**Comment by ebocher** [comment]
Could you explain a bit the problem ? thanks.

**Comment by obonin** [comment]
I don't have anything really explicit. When building H2GIS, I get the following error message:

Running org.h2gis.h2spatialext.function.spatial.mesh.MeshFunctionTest
Tests run: 21, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.45 sec <<< FAILURE! - in org.h2gis.h2spatialext.function.spatial.mesh.MeshFunctionTest
test_ST_VORONOIJTSInvalid(org.h2gis.h2spatialext.function.spatial.mesh.MeshFunctionTest)  Time elapsed: 0.026 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: java.sql.SQLException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Nothing more in the surefire-report file.

**Comment by ebocher** [comment]
Fix
